# Generated by Django 2.2.28 on 2025-02-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250210_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
